import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { StrictMode } from 'react';
import ReactDOM from 'react-dom/client';
import { Provider } from 'react-redux';
import { store } from './store';
import { AuthProvider } from './context/AuthContext';
import { initSentryWeb, Sentry } from './sentry';
import App from './App';
import './index.css';
initSentryWeb();
ReactDOM.createRoot(document.getElementById('root')).render(_jsx(StrictMode, { children: _jsx(Sentry.ErrorBoundary, { fallback: ({ error }) => (_jsx("div", { className: "min-h-screen flex items-center justify-center bg-[#FAFAF8] p-6 text-center", children: _jsxs("div", { className: "max-w-md bg-white p-8 rounded-xl border border-stone-200 shadow-sm", children: [_jsx("h2", { className: "text-xl font-bold text-stone-900 mb-2 font-display", children: "Something went wrong" }), _jsx("p", { className: "text-sm text-stone-500 mb-6", children: "An unexpected application error occurred. An error report has been logged." }), _jsx("p", { className: "text-xs text-stone-400 font-mono mb-6 bg-stone-50 p-2 rounded", children: error?.message ? String(error.message) : String(error) }), _jsx("button", { onClick: () => window.location.reload(), className: "px-5 py-2.5 bg-[#0B4F4A] hover:bg-[#083D39] text-white font-medium text-sm rounded-lg transition-colors", children: "Reload Ledger" })] }) })), children: _jsx(Provider, { store: store, children: _jsx(AuthProvider, { children: _jsx(App, {}) }) }) }) }));
