import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Sun, Moon, CalendarCheck } from 'lucide-react';
export const TopBar = ({ monthLabel = 'Current Cycle', isShared, onToggleShared, activeGroupName, onManageShared, isDark, onToggleTheme, onEndMonthClick, }) => {
    return (_jsxs("header", { className: "sticky top-0 z-30 bg-surface/90 backdrop-blur-md border-b border-border px-7 py-3 flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center gap-4", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx("div", { className: "w-8 h-8 rounded-full bg-primary/10 flex items-center justify-center text-primary", children: _jsx("span", { className: "font-display font-bold text-sm", children: "L" }) }), _jsx("div", { children: _jsx("span", { className: "font-display text-[22px] md:text-[26px] font-semibold text-text-primary tracking-tight leading-none", children: monthLabel }) })] }), _jsxs("div", { className: "hidden sm:flex items-center p-1 bg-surface-raised rounded-pill border border-border", children: [_jsx("button", { type: "button", onClick: () => onToggleShared(false), className: `px-3 py-1 rounded-pill text-xs font-semibold transition-colors duration-160 ${!isShared
                                    ? 'bg-surface text-primary shadow-sm'
                                    : 'text-text-secondary hover:text-text-primary'}`, children: "Personal" }), _jsx("button", { type: "button", onClick: () => onToggleShared(true), className: `px-3 py-1 rounded-pill text-xs font-semibold transition-colors duration-160 ${isShared
                                    ? 'bg-surface text-primary shadow-sm'
                                    : 'text-text-secondary hover:text-text-primary'}`, children: "Shared" })] }), isShared && onManageShared && (_jsxs("button", { type: "button", onClick: onManageShared, className: "flex items-center gap-1.5 px-3 py-1 bg-primary/10 hover:bg-primary/15 text-primary rounded-pill text-xs font-semibold transition-colors border border-primary/20", children: [_jsx("span", { children: activeGroupName || 'Choose Group' }), _jsx("span", { className: "text-[10px] opacity-75", children: "\u25BE" })] }))] }), _jsxs("div", { className: "flex items-center gap-3", children: [onEndMonthClick && (_jsxs("button", { type: "button", onClick: onEndMonthClick, className: "h-10 px-4 rounded-btn bg-primary hover:bg-primary-hover text-white text-sm font-semibold transition-colors duration-160 flex items-center gap-2 focus-visible:outline-2 focus-visible:outline-primary shadow-sm", children: [_jsx(CalendarCheck, { className: "w-4 h-4" }), _jsx("span", { className: "hidden sm:inline", children: "End Month" })] })), _jsx("button", { type: "button", onClick: onToggleTheme, "aria-label": "Toggle dark mode", className: "w-10 h-10 rounded-btn flex items-center justify-center text-text-secondary hover:text-text-primary hover:bg-surface-raised transition-colors duration-160 border border-transparent hover:border-border", children: isDark ? _jsx(Sun, { className: "w-4 h-4" }) : _jsx(Moon, { className: "w-4 h-4" }) })] })] }));
};
